<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Config.txt</string>
	</array>
	<key>name</key>
	<string>Trainz Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>([a-z\-\_]+[^\n\S])</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>([0-9]+([\.,])?([0-9])*)</string>
			<key>name</key>
			<string>constant.numeric.trainz_config</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>comment</key>
			<string>Simple string</string>
			<key>end</key>
			<string>(")</string>
			<key>name</key>
			<string>string.quoted.double.trainz_config</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>KUID &lt;kuid:xxxx:xxxx&gt;</string>
			<key>match</key>
			<string>((\&lt;kuid[2]?)[0-9\:]*\&gt;)</string>
			<key>name</key>
			<string>variable.parameter.kuid.trainz_config</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Closing curly bracket</string>
			<key>match</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.brace.curly.trainz_config</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-z\-\_0-9]+\n)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.object</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Container with string identifier</string>
			<key>end</key>
			<string>\{</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.trainz_config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[0-9\s]+\n)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.object</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Container with numeric identifier</string>
			<key>end</key>
			<string>\{</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.trainz_config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.trainz_config</string>
	<key>uuid</key>
	<string>f68ed429-650e-49f9-9c38-88a939f206a6</string>
</dict>
</plist>
